### PR TITLE
Recommended changes for code portability

### PR DESCRIPTION
**Pull request by Andistar12**
I had trouble getting the vm running on my Debian buster system, so I'm proposing the following changes to help make it easier for others to get the vm working out-of-the-box.

 - Lower the cmake version requirement to 3.13
 - Ship cJSON with the project to remove the external dependency (its just two source files)
 - Rewrite the vm loader to remove the dependency on bsd

I tested this on Debian 10 and Ubuntu 20.04 (Windows Subsystem for Linux) and all seems to be running fine

### CODE REVIEW

**Comment by MichalYoung** [comment]
Trying to make this work smoothly for students on Linux, including under Windows

**Comment by Andistar12** [comment]
Well I got the vm working on Windows (under CLion with libraries installed via Cygwin). I had to update the include directories for it to work but this seems to be working under Windows and Linux. If it works on your Mac then I think it's safe to merge this pull req

**Comment by MichalYoung** [comment]
Not sure why I didn't see this earlier ... or maybe I don't understand the history that github is presenting.  Either way, thanks for contributing to making this as portable as possible.

**Comment by MichalYoung** [comment]
Seems to work fine on my mac.

**Pull request merged**
